platform :ios, '7.0'

#pod 'MJRefresh', '2.4.10'
pod 'AFNetworking', '2.6.0'
pod 'SDWebImage', '3.7.3'
pod 'MJExtension', '2.5.10'
pod 'uiview-frame-helpers', '0.1.1'
pod 'Toast', '2.4'
pod 'SSKeychain', '1.2.3'
pod 'SDCycleScrollView','1.3'
pod 'US2FormValidator', '1.1.2'
pod 'RegExCategories', '1.0'
pod 'JHChainableAnimations', '1.3.0'
pod 'CTAssetsPickerController',  '2.9.5'
pod 'DZNEmptyDataSet', '1.7.1'
pod 'FLAnimatedImage', '1.0.8'